spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/development
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: release
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/release
    username: postgres
    password: admin
